# Generated by Django 3.2.7 on 2021-09-20 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категорияи',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Свойство')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='фото')),
                ('email', models.EmailField(max_length=200)),
            ],
            options={
                'verbose_name': 'Свойство',
                'verbose_name_plural': 'Свойство',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Название продукта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания товара')),
                ('time_updated', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время последнего изменения')),
                ('title_img', models.ImageField(upload_to='Shop/Article/static/images', verbose_name='Изображение')),
                ('categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorys', to='Article.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Название продукта',
                'verbose_name_plural': 'Название продукта',
            },
        ),
        migrations.CreateModel(
            name='Mycard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=20)),
                ('product', models.ManyToManyField(related_name='product', to='Article.Product')),
                ('property', models.ManyToManyField(related_name='product', to='Article.Property')),
            ],
            options={
                'verbose_name': 'VISA',
                'verbose_name_plural': 'VISA',
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(db_index=True, max_length=200)),
                ('title_img', models.ImageField(upload_to='products/', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Article.product')),
                ('Property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Article.property')),
            ],
            options={
                'verbose_name': 'карзинка',
                'verbose_name_plural': 'карзинки',
            },
        ),
    ]
